"""empty message

Revision ID: 78c7ba976658
Revises: 
Create Date: 2023-02-23 15:00:11.010467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c7ba976658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('bookid', sa.Integer(), nullable=False),
    sa.Column('booktitle', sa.String(length=50), nullable=True),
    sa.Column('bookauthor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('bookid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
